[Task CS-56] Added docstrings
cometio-solutions/recio-backend pull request #13
Opened 2021-03-29 18:00 UTC by jmysliv

2021-03-29 21:49 UTC, twistzzmc approved these changes

2021-04-01 13:03 UTC, twrdyyy requested changes

2021-04-01 13:03 UTC, twrdyyy commented on rest/models/user.py
> +        :paran pwd: plaintext password to compare
typo

2021-04-01 13:03 UTC, twrdyyy commented on rest/models/user.py
> +        :paran pwd: plaintext password to compare
```python
"""
:param pwd:
"""
```

2021-04-01 13:12 UTC, twrdyyy approved these changes

2021-04-01 13:18 UTC, merged