[Task CS-59] Error messages in authorization
cometio-solutions/recio-backend pull request #18
Opened 2021-04-08 16:13 UTC by twistzzmc

2021-04-08 16:41 UTC, jmysliv requested changes
Error messages should be in Polish.

2021-04-09 07:38 UTC, skusnierz requested changes

2021-04-09 07:38 UTC, skusnierz commented on rest/routes/user.py
> +    if len(password) < 3 or len(password) > 30 or re.match(r'^[.a-zA-Z0-9_-]+$', password) is None:
This regex doesn't include special characters like `!` ...etc. And I think in this app it is not necessary to validate input data with the use of regular expressions.

2021-04-09 07:38 UTC, skusnierz commented on rest/routes/user.py
> +        data['error'] = 'Invalid registration data'
You should return a more appropriate error message, I mean when the email format is invalid, the backend ought to return `"Wprowadzony email jest niepoprawny"` or something else, the same applies to name and password.

2021-04-09 15:44 UTC, jmysliv requested changes
Zmień errory na Polski.

2021-04-09 19:16 UTC, jmysliv reviewed
@twistzzmc Looks okay, but in this repository we require linear history, so you CAN'T merge master branch into yours. Revert merge commit and do rebase.

2021-04-10 11:06 UTC, jmysliv approved these changes

2021-04-10 12:57 UTC, skusnierz approved these changes

2021-04-10 13:04 UTC, twrdyyy approved these changes
lgtm

2021-04-10 13:09 UTC, merged