[Task CS-19] Prepare pipeline for pull-request
cometio-solutions/recio-backend pull request #2
Opened 2021-03-16 00:15 UTC by twrdyyy

2021-03-16 07:05 UTC, jmysliv requested changes

2021-03-16 07:05 UTC, jmysliv commented on .travis.yml
> +    - main
nie powinno być master?

2021-03-16 07:06 UTC, twrdyyy commented on .travis.yml
> +    - main
racja

2021-03-16 07:38 UTC, jmysliv approved these changes

2021-03-17 16:01 UTC, twistzzmc approved these changes

2021-03-17 16:16 UTC, merged