[Task CS-10] File import
cometio-solutions/recio-backend pull request #21
Opened 2021-04-10 09:07 UTC by jmysliv

2021-04-10 11:08 UTC, twistzzmc approved these changes

2021-04-11 10:14 UTC, twrdyyy requested changes

2021-04-11 10:14 UTC, twrdyyy commented on rest/models/candidate_recruitment.py
> +        if candidate_dict['test_result'] is not None and candidate_dict['average'] is not None:
Delete is not none

2021-04-11 10:36 UTC, jmysliv commented on rest/models/candidate.py
> +    pesel = db.Column(db.String(30), primary_key=True)
Pesel as a number is greater than MAX_INT in SQL, so you can't insert it into database.

2021-04-11 10:37 UTC, twrdyyy commented on rest/models/candidate.py
> +    pesel = db.Column(db.String(30), primary_key=True)
:/ +1 byczku 
Let's stay with string

2021-04-11 10:56 UTC, twrdyyy approved these changes

2021-04-11 10:56 UTC, merged