[Task CS-57] Recruitment data with candidates
cometio-solutions/recio-backend pull request #24
Opened 2021-04-14 17:56 UTC by jmysliv

2021-04-14 18:50 UTC, twrdyyy requested changes

2021-04-14 18:50 UTC, twrdyyy commented on rest/routes/recruitment.py
> +        return create_response({"error": "Błąd podczas pobierania kandydatów."}, 400, '*')
https://github.com/cometio-solutions/recio-backend/pull/23#discussion_r613505672
do this here as well

2021-04-15 11:17 UTC, twrdyyy approved these changes

2021-04-15 13:41 UTC, twistzzmc approved these changes

2021-04-15 13:43 UTC, merged