[Task CS-61] Endpoint for list of fields of study
cometio-solutions/recio-backend pull request #29
Opened 2021-04-18 18:41 UTC by twistzzmc

I've done this endpoint under filter/fields as I think all endpoints that have to do with getting stuff for filtering could be under /filter/.

2021-04-18 21:12 UTC, jmysliv requested changes
I think you misunderstood the task. Generator is only for development purpose, to make our work easier, so you can't rely on its data. When somebody will import real data, your endpoint won't work. Also return full major object not only name, some majors may have the same name but they can be at different faculties. I think you should also rename endpoint to something like `/majors'. The fact that this data will be used for filtering doesn't mean we won't use them somewhere else also.

2021-04-21 15:49 UTC, jmysliv approved these changes

2021-04-21 18:50 UTC, skusnierz approved these changes

2021-04-21 18:50 UTC, skusnierz commented
Please resolve confilcts

2021-04-22 16:59 UTC, merged