[Task CS-72] Endpoint for candidates origins
cometio-solutions/recio-backend pull request #31
Opened 2021-04-27 17:20 UTC by twistzzmc

Wasn't sure if I should also get regions and Poland starting with lowercase. Decided against it. Currently all regions and countries ought to start with a capital letter in database. Plus the regions with '-' in the middle shouldn't have spaces, but for the two Polish regions I am checking for it.

2021-04-27 18:16 UTC, skusnierz approved these changes
LGTM :D

2021-04-28 15:35 UTC, jmysliv approved these changes

2021-04-28 15:40 UTC, jmysliv requested changes

2021-04-28 15:40 UTC, jmysliv commented on rest/routes/origins.py
> +                origins[candidate.region] += 1
I think it's better to change candidate region to lowercase, then remove all spaces, and finally compare with your keys. Thanks to that you will avoid key error.

2021-05-03 18:58 UTC, jmysliv approved these changes

2021-05-03 18:59 UTC, merged