Cs 9
cometio-solutions/recio-backend pull request #5
Opened 2021-03-18 20:06 UTC by jmysliv

2021-03-18 20:56 UTC, twrdyyy commented
@jmysliv fix pylint errors plox

2021-03-18 21:25 UTC, skusnierz requested changes

2021-03-18 21:27 UTC, jmysliv commented on requirements.txt
> +pytest
@twrdyyy tak kazał, też mu to mówiłem

2021-03-18 21:34 UTC, skusnierz commented on requirements.txt
> +pytest
@jmysliv can you please take that project seriously for once? You seem to be joking right now and this is a serious task

2021-03-18 21:51 UTC, jmysliv commented on entrypoint.sh
> +echo "Installing requirements..."
no

2021-03-18 22:27 UTC, twistzzmc approved these changes

2021-03-20 10:27 UTC, skusnierz approved these changes

2021-03-20 18:00 UTC, merged